title: ExcelFix24
url: "https://www.excelfix24.com"
baseurl: ""
remote_theme: pages-themes/hacker@v0.2.0


# Include Sass partials bundled with the remote theme.
sass:
  sass_dir: assets/css/_sass
  style: compressed

collections:
  pages:
    output: true
    permalink: /:path/


